DecisionTreeClassifier:
  max_depth:
    - 3
    - 5
    - 10
    - 20
  min_samples_split:
    - 2
    - 5
    - 10
    - 20
  min_samples_leaf:
    - 1
    - 5
    - 10
    - 20
  max_features:
    - auto
    - sqrt
    - log2
  criterion:
    - gini
    - entropy
    - log_loss

RandomForestClassifier:
  max_depth:
    - 10
    - 20
    - 30
  n_estimators:
    - 50
    - 100
    - 200
    - 300
    - 500
  min_samples_split:
    - 2
    - 5
    - 10
    - 20
  min_samples_leaf:
    - 1
    - 2
    - 5
    - 10
  max_features:
    - sqrt
    - log2
  max_samples:
    - 0.5
    - 0.75
    - 1.0

XGBClassifier:
  n_estimators:
    - 50
    - 100
    - 200
    - 300
    - 500
  learning_rate:
    - 0.01
    - 0.03
    - 0.05
    - 0.1
    - 0.2
  max_depth:
    - 3
    - 5
    - 8
    - 10
  gamma:
    - 1
    - 3
    - 5
    - 7
    - 10
  min_child_weight:
    - 2
    - 5
    - 8
    - 10

