numerical_columns:
  - lead_time
  - arrival_date_year
  - arrival_date_week_number
  - arrival_date_day_of_month
  - stays_in_weekend_nights
  - stays_in_week_nights
  - adults
  - children
  - babies
  - is_repeated_guest
  - previous_cancellations
  - previous_bookings_not_canceled
  - booking_changes
  - agent
  - days_in_waiting_list
  - adr
  - required_car_parking_spaces
  - total_of_special_requests

categorical_columns:
  - hotel
  - arrival_date_month
  - meal
  - country
  - market_segment
  - distribution_channel
  - reserved_room_type
  - assigned_room_type
  - deposit_type
  - customer_type
  - reservation_status
  - reservation_status_date

target_variable:
  - is_caneled
