data_ingestion:
  source_url: "https://drive.google.com/uc?id=14cOM7gDRkhIo7qye4lI_9MK02vDAkqqU"
  download_path: "artifacts/data_ingestion/hotel_cancellation.csv"

data_transform:
  input_path: "artifacts/data_ingestion/hotel_cancellation.csv"
  x_train_output_path: "artifacts/data_transform/x_train.csv"
  x_test_output_path: "artifacts/data_transform/x_test.csv"
  y_train_output_path: "artifacts/data_transform/y_train.csv"
  y_test_output_path: "artifacts/data_transform/y_test.csv"

  columns_to_drop:
    - email
    - phone-number
    - credit_card
    - name
    - company

  dtype_convertion:
    children: int64
    agent: int64
    reservation_status_date: datetime64[ms]

  missing_values:
    categorical:
      - country
    numerical:
      - children
      - agent

  outlier_columns:
    iqr:
      - arrival_date_week_number
    log:
      - lead_time
      - agent
      - adr

data_validation:
  input_path: "artifacts/data_transform/X.csv"
  dtypes:
    number: 23
    object: 11
  shape:
    rows: 48050
    columns: 34

model_training:
  encodings:
    ordinal_encoder:
      - hotel
      - meal
      - distribution_channel
      - deposit_type
      - customer_type
      - reservation_status
    count_encoder:
      - country
    target_encoder:
      - assigned_room_type
      - reserved_room_type
      - market_segment
      - arrival_date_month

