data_ingestion:
  source_url: "https://drive.google.com/uc?id=14cOM7gDRkhIo7qye4lI_9MK02vDAkqqU"
  download_path: "artifacts/data_ingestion/hotel_cancellation.csv"

data_cleaning:
  input_path: "artifacts/data_ingestion/hotel_cancellation.csv"
  df_output_path: "artifacts/data_cleaning/cleaned.csv"

  columns_to_drop:
    - email
    - phone-number
    - credit_card
    - name
    - company
    - reservation_status_date
    - reservation_status

  dtype_convertion:
    children: int64
    agent: int64

  missing_values:
    categorical:
      - country
    numerical:
      - children
      - agent

  outlier_columns:
    iqr:
      - arrival_date_week_number
    log:
      - lead_time
      - agent
      - adr

data_validation:
  input_path: "artifacts/data_cleaning/cleaned.csv"
  dtypes:
    number: 19
    object: 10
  shape:
    rows: 48047
    columns: 30
  classes: 2

data_preprocessing:
  df_input_path: "artifacts/data_cleaning/cleaned.csv"
  encodings:
    ordinal_encoder:
      - hotel
      - meal
      - distribution_channel
      - deposit_type
      - customer_type
    count_encoder:
      - country
      - assigned_room_type
      - reserved_room_type
      - market_segment
      - arrival_date_month
  train_output_path: "artifacts/data_preprocessing/train.csv"
  test_output_path: "artifacts/data_preprocessing/test.csv"
  pipeline_path: "artifacts/data_preprocessing/preprocessor.joblib"

model_selection:
  train_input_path: "artifacts/data_preprocessing/train.csv"
  best_model_info_path: "artifacts/model_selection/best_model.json"

model_training:
  train_input_path: "artifacts/data_preprocessing/train.csv"
  preprocessor_path: "artifacts/data_preprocessing/preprocessor.joblib"
  best_model_info_path: "artifacts/model_selection/best_model.json"
  pipeline_path: "model/trained/pipeline.joblib"

model_evaluation:
  pipeline_path: "model/trained/pipeline.joblib"
  test_data_path: "artifacts/data_preprocessing/test.csv"
  output_path: "artifacts/model_evaluation/metrics.json"


